### ISSUE TITLE
How to change color of bottomNavBar item when selected programmatically

### ISSUE THREAD

**Issue by KishanViramgama** [jitinsharma/BottomNavBar#1]
![47417461-a13c9080-d795-11e8-8cb5-c936b70aaac9](https://user-images.githubusercontent.com/18188589/64907356-e6034a00-d70e-11e9-91a9-6d9c74df2a87.png)

**Comment by jitinsharma** [comment]
Maybe i can add a public to do that according to position given. Let me check

**Comment by KishanViramgama** [comment]
> Maybe i can add a public to do that according to position given. Let me check

thank you for reply great library.
and also need to clear selected option indicator.
